28 updating the text viewer
klab-ilc-cnr/maia-fe pull request #154
Opened 2024-03-01 09:13 UTC by cienco

2024-03-01 10:09 UTC, MPapini91 requested changes
Opening Decameron with Edge and Firefox, I realized that the annotation labels are far away from the text, a distance that shrinks and disappears after a bit of scrolling. Can you run a check on this?
<img width="806" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/61142119/b1663837-6309-4907-aaba-6ad8d0223c34">

<img width="803" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/61142119/46cdfc6b-209c-4e19-a196-ab1a5143f89f">

2024-03-04 10:13 UTC, cienco commented
> Opening Decameron with Edge and Firefox, I realized that the annotation labels are far away from the text, a distance that shrinks and disappears after a bit of scrolling. Can you run a check on this? <img alt="image" width="806" src="https://private-user-images.githubusercontent.com/61142119/309223590-b1663837-6309-4907-aaba-6ad8d0223c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDcyNzIsIm5iZiI6MTcwOTU0Njk3MiwicGF0aCI6Ii82MTE0MjExOS8zMDkyMjM1OTAtYjE2NjM4MzctNjMwOS00OTA3LWFhYmEtNmFkOGQwMjIzYzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEwMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMWFhZmUwODNkOWUxY2U0YjU5NmNiMTlkYzEzYjBmYmU3ZjgxY2RkMGQ4ZTVlOTE1YTY0MjVjMWJkMTI0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZLYRlm6MR9ur6yieg6d5uL6viuJ3rNDIHQ-lZ6k5Ws">
> 
> <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/61142119/309223710-46cdfc6b-209c-4e19-a196-ab1a5143f89f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDcyNzIsIm5iZiI6MTcwOTU0Njk3MiwicGF0aCI6Ii82MTE0MjExOS8zMDkyMjM3MTAtNDZjZGZjNmItMjA5Yy00ZTE5LWExOTYtYWIxYTUxNDNmODlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEwMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNzllNWQ3ODQ4MjgxMjhlMmM4NzdiMTVhMmQzOTdkYWFkMTg2M2Q3Y2QyNjE4OTZiMzg2YWQxMTM5MWQwYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIx7bHKGeCdn437Gh1F2PscvKGTarkZzQRu9YCjDhjY">

This problem is related to dirty data coming from backend. I wasn't able to reproduce this issue generating similar data using text editor. It's working correctly.

2024-03-04 10:16 UTC, cienco commented on src/app/models/texto/paginated-response.ts
Ok I will fix this directly in the #27 as I moved some part of the code

2024-03-04 15:43 UTC, MPapini91 commented
> @cienco I noticed a problem with infinite scroll, you have a jump forward reading on the first scroll which is not correct. I have uploaded to Teams an example video on "Front-end"

@cienco  will you address this issue on this PR or on 27?

2024-03-05 10:04 UTC, cienco commented
> > @cienco I noticed a problem with infinite scroll, you have a jump forward reading on the first scroll which is not correct. I have uploaded to Teams an example video on "Front-end"
> 
> @cienco will you address this issue on this PR or on 27?

yes I can see the problem I'll fix it in the #155

2024-03-05 11:56 UTC, cienco commented
> > > @cienco I noticed a problem with infinite scroll, you have a jump forward reading on the first scroll which is not correct. I have uploaded to Teams an example video on "Front-end"
> > 
> > 
> > @cienco will you address this issue on this PR or on 27?
> 
> yes I can see the problem I'll fix it in the #155

Now should work

2024-03-07 10:49 UTC, merged