27 adding the navigation tree of the text viewer sections in the panel
klab-ilc-cnr/maia-fe pull request #155
Opened 2024-03-04 08:48 UTC by cienco

merge and review the #154 before this one

2024-03-04 11:21 UTC, MPapini91 commented
@cienco  , could you please use English for documentation? Thank you

2024-03-04 17:12 UTC, cienco commented
> @cienco , could you please use English for documentation? Thank you

sure it's done

2024-03-04 17:24 UTC, MPapini91 commented on src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts
What was the problem with Firefox in this case?

2024-03-05 08:29 UTC, cienco commented on src/app/pages/workspace/workspace-text-window/workspace-text-window.component.ts
scrolling down was not working in firefox only

2024-03-06 16:36 UTC, MPapini91 requested changes

2024-03-06 16:36 UTC, MPapini91 commented on src/app/services/workspace.service.ts
> +
Add jsdoc

2024-03-07 10:45 UTC, MPapini91 approved these changes

2024-03-07 10:49 UTC, merged